/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GraduationProjectManagement.Controller;

import java.sql.Connection;

public class App {

    public static void main(String[] args) {
        new Auth_Controller();
//        ConnectDB_Controller loginDB_Controller = new ConnectDB_Controller();

//        Connection cnn = ConnectDB.getConnectDB();
//        System.out.println(new App().getGreeting());
    }
}
